// Auto-Generated by FAKE; do not edit
namespace System

open System.Reflection

[<assembly: AssemblyTitleAttribute("DynamoDb.Ok")>]
[<assembly: AssemblyProductAttribute("DynamoDb.Ok")>]
[<assembly: AssemblyDescriptionAttribute("")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    [<Literal>]
    let AssemblyTitle = "DynamoDb.Ok"

    [<Literal>]
    let AssemblyProduct = "DynamoDb.Ok"

    [<Literal>]
    let AssemblyDescription = ""

    [<Literal>]
    let AssemblyVersion = "0.0.1"

    [<Literal>]
    let AssemblyFileVersion = "0.0.1"
