version: 2.1

cache_key: &cache_key cache-v1-{{ checksum "paket.lock" }}

jobs:
    build:
        docker:
            - image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
        steps:
            - checkout
            - restore_cache:
                  key: *cache_key
            - run: ./build.sh
            - save_cache:
                  key: *cache_key
                  paths:
                      - packages

workflows:
    version: 2
    build:
        jobs:
            - build
