// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DynamoDb.Ok.Tests")>]
[<assembly: AssemblyProductAttribute("DynamoDb.Ok")>]
[<assembly: AssemblyVersionAttribute("0.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-05-02T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.5")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","8165db742f1ac59500e82a4680febc3bbe83df82")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DynamoDb.Ok.Tests"
    let [<Literal>] AssemblyProduct = "DynamoDb.Ok"
    let [<Literal>] AssemblyVersion = "0.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-05-02T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.5"
    let [<Literal>] AssemblyInformationalVersion = "0.0.5"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "8165db742f1ac59500e82a4680febc3bbe83df82"
