// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("DynamoDb.Ok.Tests")>]
[<assembly: AssemblyProductAttribute("DynamoDb.Ok")>]
[<assembly: AssemblyVersionAttribute("0.0.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-04-30T00:00:00.0000000+01:00")>]
[<assembly: AssemblyFileVersionAttribute("0.0.3")>]
[<assembly: AssemblyInformationalVersionAttribute("0.0.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","4d7c15cff1505ac4478c96cac036c6c5df4711e7")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "DynamoDb.Ok.Tests"
    let [<Literal>] AssemblyProduct = "DynamoDb.Ok"
    let [<Literal>] AssemblyVersion = "0.0.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-04-30T00:00:00.0000000+01:00"
    let [<Literal>] AssemblyFileVersion = "0.0.3"
    let [<Literal>] AssemblyInformationalVersion = "0.0.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "4d7c15cff1505ac4478c96cac036c6c5df4711e7"
