name: Build

on:
  push:
    branches-ignore:    
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dotnet: ['8.x.x']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet tool restore
      - run: dotnet paket restore
      - run: dotnet build
      - run: dotnet run -p ./tests/**/*.fsproj
