name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        dotnet: [3.1.201]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: dotnet tool restore
      - run: dotnet restore
      - run: dotnet build -c Release -o ./build
      - run: dotnet fornax build
        working-directory: docs
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_public
          publish_branch: gh-pages
          force_orphan: true
